   
    create table SHORTCUTS (
        shortcut_id bigint generated by default as identity,
        redirect varchar(1024),
        url_key varchar(1024),
        primary key (shortcut_id)
    );

    create table SHORTCUTS_APP (
        object_id bigint not null,
        primary key (object_id)
    );
