   
    create table shortcuts (
        shortcut_id bigint generated by default as identity,
        redirect varchar(1024),
        url_key varchar(1024),
        primary key (shortcut_id)
    );

    create table shortcuts_app (
        object_id bigint not null,
        primary key (object_id)
    );
