/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.librecms.ui.contentsections.documents;

import org.libreccm.l10n.GlobalizationHelper;
import org.librecms.contentsection.ContentItem;

import java.util.ResourceBundle;

/**
 * Describes the create for a document (content item).
 *
 * @author <a href="mailto:jens.pelzetter@googlemail.com">Jens Pelzetter</a>
 */
public interface MvcDocumentCreateStep {

    /**
     * Get the class implementing the sub resource implemeting the logic for the
     * step. This must be a CDI bean.
     *
     * @return The sub resource class implementing the create step.
     */
    Class<?> getSubResourceClass();

    /**
     * The document type generated by the create step described by an instance
     * of this class.
     *
     * @return Document type generated.
     */
    Class<? extends ContentItem> getDocumentType();

    /**
     * Localized description of the create step. The current locale as returned
     * by {@link GlobalizationHelper#getNegotiatedLocale()} should be used to
     * select the language variant to return.
     *
     * @return The localized description of the create step.
     */
    String getDescription();

    /**
     * Returns {@link ResourceBundle} providing the localized description of the
     * create step.
     *
     * @return The {@link ResourceBundle} providing the localized description of
     *         the create step.
     */
    String getBundle();

}
